#!bash

# bash completion for os

have os && {
_os-cmd()
{
local cur prev

saveIFS=$IFS
IFS=$'\n'    # this will allow filenames with spaces (but not filenames with newlines)
COMPREPLY=( $( os auto-complete ${COMP_CWORD} "${COMP_WORDS[1]}" "${COMP_WORDS[2]}" "${COMP_WORDS[3]}" "${COMP_WORDS[4]}" "${COMP_WORDS[5]}" ) )
IFS=$saveIFS

return 0
}
complete  -o nospace -F _os-cmd os

}
